/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <regex.h>

#include "fsTable.h"
#include "log.h"
#include "command.h"
#include "util.h"

/** Initializes the fsTable module */
void
init_fsTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_fsTable();
}

static struct timeval volume_cache_timestamp = { 0, 0 };
static int last_index_used = 0;
void update_volumes();

/** Initialize the fsTable table by defining its contents and how it's structured */
void
initialize_table_fsTable(void)
{
    static oid fsTable_oid[] = {1,3,6,1,4,1,20038,2,1,4,1};
    size_t fsTable_oid_len   = OID_LENGTH(fsTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "fsTable",     fsTable_handler,
              fsTable_oid, fsTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: fsIndex */
                           0);
    table_info->min_column = COLUMN_FSINDEX;
    table_info->max_column = COLUMN_FSSMARTMESSAGE;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = fsTable_get_first_data_point;
    iinfo->get_next_data_point  = fsTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    update_volumes();
}

    /* Typical data structure for a row entry */
struct fsTable_entry {
    /* Index values */
    long fsIndex;

    /* Column values */
    char *fsFilesystem;
    size_t fsFilesystem_len;
    char *fsMountpoint;
    size_t fsMountpoint_len;
    u_long fsSize;
    u_long fsUsed; 
    u_long fsAvail;
    u_long fsUtilization;
    u_long fsInodesUsed;
    u_long fsInodesFree;
    u_long fsInodesUtilization;
    long fsWriteable;
    long fsRemovable;
    long fsBootable;
    long fsSmartStatus;
    char *fsSmartMessage;
    size_t fsSmartMessage_len;
    
    /* Obsolescence checking */
    time_t last_seen;

    /* Illustrate using a simple linked list */
    struct fsTable_entry *next;
};

static struct fsTable_entry  *fsTable_head;

/* create a new row in the (unsorted) table */
struct fsTable_entry *
fsTable_createEntry(
                 long  fsIndex) {
    struct fsTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct fsTable_entry);
    if (!entry)
        return NULL;

    entry->fsIndex = fsIndex;
    entry->next = fsTable_head;
    entry->fsWriteable = -1;
    entry->fsRemovable = -1;
    entry->fsBootable = -1;
    entry->fsSmartStatus = -1;
    fsTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
fsTable_removeEntry( struct fsTable_entry *entry ) {
    struct fsTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = fsTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        fsTable_head = ptr->next;
    else
        prev->next = ptr->next;
        
    if (entry->fsFilesystem) free (entry->fsFilesystem);
    if (entry->fsMountpoint) free (entry->fsMountpoint);

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
fsTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = fsTable_head;
    return fsTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
fsTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct fsTable_entry *entry = (struct fsTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->fsIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}

void update_volume_disk (struct fsTable_entry *entry)
{
  /* Uses 'diskutil' to update the disk referenced in disk_name */
  char *data = x_command_run_va("diskutil info %s", entry->fsFilesystem);
  if (!data)
  {
    x_printf ("ERROR: Failed to get data from 'diskutil info %s'\n", entry->fsFilesystem);
    return; 
  }
  size_t data_len = strlen(data);

  char *writeable_str = NULL;
  size_t writeable_str_len = 0;
  if (extract_string_from_regex(data, data_len, "Read-Only Volume:[ ]+(\\w+)$", &writeable_str, &writeable_str_len))
  {
    entry->fsWriteable = !extract_boolean_from_regex(data, data_len, "Read-Only Volume:[ ]+(\\w+)$");
  }
  else
  {
    entry->fsWriteable = !extract_boolean_from_regex(data, data_len, "Read Only:[ ]+(\\w+)$");
  }

  entry->fsRemovable = extract_boolean_from_regex(data, data_len, "Ejectable:[ ]+(\\w+)$");
  
  char *boot_str = NULL;
  size_t boot_str_len = 0;
  if (extract_string_from_regex(data, data_len, "Bootable:[ ]+(.*)$", &boot_str, &boot_str_len))
  {
    if (!strcmp(boot_str, "Is bootable"))
    {
      entry->fsBootable = 1;
    }
    else if (!strcmp(boot_str, "Not bootable"))
    {
      entry->fsBootable = 0;
    }
  }
  if (boot_str) free (boot_str);
  
  if (extract_string_from_regex(data, data_len, "SMART Status:[ ]+(.*)$", &entry->fsSmartMessage, &entry->fsSmartMessage_len))
  { 
    if (!strcmp(entry->fsSmartMessage, "Verified")) entry->fsSmartStatus = 1;
    else if (!strcmp(entry->fsSmartMessage, "Not Supported")) entry->fsSmartStatus = 0;
    else entry->fsSmartStatus = 2;
  } 

  free (data);
}

void update_volumes()
{
  struct timeval now;
  gettimeofday(&now, NULL);
  
  char *data = x_command_run("df -mi");
  if (!data) return;
  size_t data_len = strlen(data);

  regex_t re;
    
  int rc = regcomp(&re,
                   "^(.*)[ ]+"     /*  1 Filesystem */
                   "([0-9]+)[ ]+"  /*  2 1M-blocks */
                   "([0-9]+)[ ]+"  /*  3 Used */
                   "([0-9]+)[ ]+"  /*  4 Available */
                   "([0-9]+)%[ ]+" /*  5 Capacity */
                   "([0-9]+)[ ]+"  /*  6 iused */
                   "([0-9]+)[ ]+"  /*  7 ifree */
                   "([0-9]+)%[ ]+" /*  8 %iused */
                   "(.*)$"         /*  9 Mounted on */,
                   REG_EXTENDED | REG_NEWLINE);
  if (rc) {
    x_printf("ERROR: update_volumes failed to compile regex");
    free(data);
    return;
  }

  const char *start = data;
  const size_t ocount = 30;
  regmatch_t ovector[ocount];

  while(1)
  {
    memset(ovector, 0, sizeof(ovector));
    rc = regexec(&re, start, ocount, ovector, 0);

    if (rc == REG_NOMATCH)
    {
      break;
    }

    /* Other matching errors are not recoverable. */
    if (rc == 0)
    {
      /* Matched a volume */
      char *volname_str = NULL;
      extract_string_in_group(start, ovector[9], &volname_str, NULL);
      
      struct fsTable_entry *entry = fsTable_head;
      while (entry)
      {
        if (!strcmp(volname_str, entry->fsMountpoint)) break;
        entry = entry->next;
      }
      if (!entry)
      {
        last_index_used++;
        entry = fsTable_createEntry(last_index_used);
        entry->fsMountpoint = strdup(volname_str);
        entry->fsMountpoint_len = strlen (entry->fsMountpoint);
      }
      entry->last_seen = now.tv_sec;
      free (volname_str);
      volname_str = NULL;
      
      extract_string_in_group(start, ovector[1], &entry->fsFilesystem, &entry->fsFilesystem_len);

      entry->fsSize = extract_uint_in_group(start, ovector[2]);
      entry->fsUsed = extract_uint_in_group(start, ovector[3]);
      entry->fsAvail = extract_uint_in_group(start, ovector[4]);
      entry->fsUtilization = extract_uint_in_group(start, ovector[5]);
      entry->fsInodesUsed = extract_uint_in_group(start, ovector[6]);
      entry->fsInodesFree = extract_uint_in_group(start, ovector[7]);
      entry->fsInodesUtilization = extract_uint_in_group(start, ovector[8]);

      /* Update extra info on the disk from diskutil */
#ifdef __APPLE__
      if (entry->fsFilesystem && strstr(entry->fsFilesystem, "/dev/")) update_volume_disk(entry);
#endif
      
      start += ovector[0].rm_eo;
    }
    else
    {
      regfree(&re);    /* Release memory used for the compiled pattern */
      return;
    }  
  }
  
  /* Clean up */
  regfree(&re);
  
  /* Check for obsolete entries */
  struct fsTable_entry *entry = fsTable_head;
  while (entry)
  {
    struct fsTable_entry *next = entry->next;
    if (entry->last_seen != now.tv_sec)
    {
      /* Entry is obsolete */
      fsTable_removeEntry(entry);
    }
    entry = next;
  }

  /* Update cache timestamp */
  gettimeofday(&volume_cache_timestamp, NULL);    
  
  /* Clean up */
  free (data);
  data = NULL;
  data_len = 0;
}

#define MAX_CACHE_TIMEOUT 10

void update_volumes_if_necessary()
{
  struct timeval now;
  gettimeofday(&now, NULL);
  if ((now.tv_sec - volume_cache_timestamp.tv_sec) > MAX_CACHE_TIMEOUT)
  { 
    update_volumes(); 
  }
}

/** handles requests for the fsTable table */
int
fsTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct fsTable_entry          *table_entry;

    update_volumes_if_necessary();

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct fsTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_FSINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->fsIndex);
                break;
            case COLUMN_FSFILESYSTEM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->fsFilesystem,
                                          table_entry->fsFilesystem_len);
                break;
            case COLUMN_FSMOUNTPOINT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->fsMountpoint,
                                          table_entry->fsMountpoint_len);
                break;
            case COLUMN_FSSIZE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->fsSize);
                break;
            case COLUMN_FSUSED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->fsUsed);
                break;
            case COLUMN_FSAVAIL:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->fsAvail);
                break;
            case COLUMN_FSUTILIZATION:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->fsUtilization);
                break;
            case COLUMN_FSWRITEABLE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->fsWriteable);
                break;
            case COLUMN_FSREMOVABLE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->fsRemovable);
                break;
            case COLUMN_FSBOOTABLE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->fsBootable);
                break;
            case COLUMN_FSSMARTSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->fsSmartStatus);
                break;
            case COLUMN_FSSMARTMESSAGE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->fsSmartMessage,
                                          table_entry->fsSmartMessage_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}

void test_fsTableVolumes()
{
    update_volumes();
    
    // dump all entries
    for (struct fsTable_entry *entry = fsTable_head; entry; entry = entry->next)
    {
        printf("fsIndex=%ld\n", entry->fsIndex);
        
        printf("\tfsFilesystem=%s\n", entry->fsFilesystem);
        printf("\tfsMountpoint=%s\n", entry->fsMountpoint);

        printf("\tfsSize=%lu\n", entry->fsSize);
        printf("\tfsUsed=%lu\n", entry->fsUsed);
        printf("\tfsAvail=%lu\n", entry->fsAvail);
        printf("\tfsUtilization=%lu\n", entry->fsUtilization);
        printf("\tfsInodesUsed=%lu\n", entry->fsInodesUsed);
        printf("\tfsInodesFree=%lu\n", entry->fsInodesFree);
        printf("\tfsInodesUtilization=%lu\n", entry->fsInodesUtilization);

        printf("\tfsWriteable=%ld\n", entry->fsWriteable);
        printf("\tfsRemovable=%ld\n", entry->fsRemovable);
        printf("\tfsBootable=%ld\n", entry->fsBootable);
        printf("\tfsSmartStatus=%ld\n", entry->fsSmartStatus);

        printf("\tfsSmartMessage=%s\n", entry->fsSmartMessage);
    }
}
